#!/usr/bin/env bash

if [ ! -e .env ]; then
    cp .env.dist .env
fi

if [ "$1" == "up" ]; then
    if [ ! -d docker/var/.ssh/id_rsa ]; then
        cp ~/.ssh/id_rsa docker/php/var/.ssh/
        cp ~/.ssh/id_rsa.pub docker/php/var/.ssh/
    fi
    docker-compose "$@"
elif [ "$1" == "enter-root" ]; then
    docker-compose exec -u root php bash
elif [ "$1" == "enter" ]; then
    docker-compose exec -u utente php bash
elif [ $# -gt 0 ]; then
    docker-compose "$@"
else
    docker-compose ps
fi
