version: '3'

services:
  php:
    build: docker/php
    tty: true # -t option in docker
    stdin_open: true # -i option in docker
    hostname: ${HOSTNAME}
    volumes:
      - ./:/var/www/app
    environment:
      - APP_ENV=${APP_ENV}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL}
      - GIT_USER_NAME=${GIT_USER_NAME}
